apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgis-h3
          image: postgis-h3
          ports:
            - containerPort: 5432
